-------------------------------------------------------------------------------
--Each new term in the Fibonacci sequence is generated by adding the previous
--two terms. By starting with 1 and 2, the first 10 terms will be:

--1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

--By considering the terms in the Fibonacci sequence whose values do not
--exceed four million, find the sum of the even-valued terms.
-------------------------------------------------------------------------------

import Data.List

fibs = 0 : 1 : [p + q | (p,q) <- zip fibs (tail fibs)]

sum_even_fibs :: Integer -> Integer
sum_even_fibs n = sum $ takeWhile (< n) [m | m <- fibs, m `mod` 2 == 0]
